$AIRSPYONE_HOST_SOURCES="$CS_SOURCES/airspyone_host"
if (-not ($AIRSPYONE_HOST_SOURCES | Test-Path)) {
    git clone https://github.com/airspy/airspyone_host $AIRSPYONE_HOST_SOURCES
}

$AIRSPYONE_HOST_TARGET="$CS_TARGET/airspyone_host"
$AIRSPYONE_HOST_INSTALL="$CS_INSTALL/airspy"
if (-not ($AIRSPYONE_HOST_TARGET | Test-Path)) {
    $null=New-Item $AIRSPYONE_HOST_TARGET -ItemType Directory
    cmake -B $AIRSPYONE_HOST_TARGET -G $CS_GENERATOR -A $CS_BUILD_ARCH $AIRSPYONE_HOST_SOURCES `
        -DTHREADS_PTHREADS_WIN32_LIBRARY:PATH="$PTHREADS_LIBRARIES" `
        -DTHREADS_PTHREADS_INCLUDE_DIR:PATH="$PTHREADS_INCLUDE_DIR" `
        -DLIBUSB_INCLUDE_DIR:PATH="$LIBUSB_INCLUDE_DIR" `
        -DLIBUSB_LIBRARIES:PATH="$LIBUSB_LIBRARIES" `
        -DCMAKE_INSTALL_PREFIX="$AIRSPYONE_HOST_INSTALL"
    cmake --build $AIRSPYONE_HOST_TARGET --config Release --target install
}
$AIRSPY_INCLUDE_DIR="$CS_INSTALL/airspy/include/"
$AIRSPY_LIBRARIES="$CS_INSTALL/airspy/bin/airspy.lib"
Copy-Item -Path "$AIRSPYONE_HOST_INSTALL/bin/*.dll" -Destination "$CS_INSTALL/SoapySDR/bin/"


$SOAPYAIRSPY_SOURCES="$CS_SOURCES/SoapyAirspy"
if (-not ($SOAPYAIRSPY_SOURCES | Test-Path)) {
    git clone https://github.com/pothosware/SoapyAirspy $SOAPYAIRSPY_SOURCES
}


$SOAPYAIRSPY_TARGET="$CS_TARGET/SoapyAirspy"
if (-not ($SOAPYAIRSPY_TARGET | Test-Path)) {
    $null=New-Item $SOAPYAIRSPY_TARGET -ItemType Directory
    cmake -B $SOAPYAIRSPY_TARGET -G $CS_GENERATOR -A $CS_BUILD_ARCH $SOAPYAIRSPY_SOURCES `
        -DLIBAIRSPY_LIBRARIES:PATH="$AIRSPY_LIBRARIES" `
        -DLIBAIRSPY_INCLUDE_DIRS:PATH="$AIRSPY_INCLUDE_DIR" `
        -DCMAKE_INSTALL_PREFIX:PATH="$SOAPY_SDR_INSTALL" `
        -DCMAKE_PREFIX_PATH:PATH="$SOAPY_SDR_INSTALL" `
        -DSOAPY_SDR_ROOT="$SOAPY_SDR_INSTALL" 
    cmake --build $SOAPYAIRSPY_TARGET --config $CS_BUILD_TYPE --target install
}

